frequency: 50  # Hz

sensor_timeout: 0.1

two_d_mode: true

# Wheel odometry parameters
odom0: /odom
odom0_config: [false, false, false,
               false, false, false,
               true, true, false,
               false, false, true,
               false, false, false]
odom0_differential: false
odom0_queue_size: 10

# IMU parameters
imu0: /mobile_base/sensors/imu_data
imu0_config: [false, false, false,
              true, true, false,
              false, false, false,
              true, true, true,
              false, false, false]
imu0_differential: false
imu0_queue_size: 10
imu0_remove_gravitational_acceleration: true

# Base frame and odom frame parameters
base_link_frame: base_link
odom_frame: odom
world_frame: odom

publish_tf: true
